version: '3'
services:
  pypicloud:
    command: sh -c '/wait-for redis:6379 -- uwsgi --die-on-term /etc/pypicloud/config.ini'
    depends_on:
      - redis
    image: stevearc/pypicloud
    expose:
      - 8080
    volumes:
      - ./config-redis.ini:/etc/pypicloud/config.ini:ro
      - ./wait-for:/wait-for:ro
      - data:/data
  redis:
    image: redis
    volumes:
      - data
        
volumes:
  data:
    driver: local
     
    
